### PR TITLE
Fixes on EDF konnector

### LINKED ISSUE #670: EDF konnector pops a notification even when nothing seems to be happening
the notification is empty. @jacquarg can you check this?

### PR DESCRIPTION
**Pull request by jacquarg**
Fix #670 :
* fix connector stop if no consumption statements available
* fix empty notification even if nothing were added.
* add day to bill file name (ex 2016-12-18-facture_EDF.pdf
* reduce to warning level, log about no edelia data.

Do I miss something ?

### CODE REVIEW

**Comment by ZeHiro** [comment]
@jacquarg looks like your forgot about the linter :)

**Comment by ZeHiro** [comment]
And the small problem on the name of the files, bit i can handle it

**Comment by jacquarg** [comment]
I fixed the name file problem (but forgot to mention it).

**Comment by ZeHiro** [comment]
Oups didn't read the code.

**Comment by ZeHiro** [comment]
LGTM, I merge

**Pull request merged**
