### PR TITLE
Fix encryption of passwords for konnectors with object format for fields

### PR DESCRIPTION
**Pull request by nono**
cc: @poupotte

### CODE REVIEW

**Comment by nono** [comment]
@doubleface the contributing guide says:

> you do not need to build app to submit a PR

Am I missing something?

**Comment by doubleface** [comment]
Oh sorry, I suppose I am missing something. So the build is done when the pullrequest is accepted ?

**Comment by doubleface** [comment]
Since this pullrequest is for the core and not a konnector, I supposed it would be different. I is just easier to test it directly in a cozy when the build part comes with the pullrequest.

**Comment by nono** [comment]
I think that @aenario builds just before publishing on npm

**Comment by poupotte** [comment]
It's ok for me :+1:

**Pull request merged**
