### PR TITLE
Added podcasts konnector

### PR DESCRIPTION
**Pull request by babolivier**
Added a konnector so you can import audio podcasts directly in your Cozy's files and listen to them in [cozy-music](https://github.com/cozy-labs/cozy-music).

### CODE REVIEW

**Comment by frankrousseau** [comment]
Wow another awesomeness by @babolivier!

Could you run the linter on it? Sorry to ask additional work but it's written in the [contributing rules](https://github.com/cozy-labs/konnectors#contributing-rules).

**Comment by babolivier** [comment]
Indeed @frankrousseau, I missed that (along adding the konnector to the list). Will do it tomorrow.

**Comment by babolivier** [comment]
@frankrousseau I complied to the linter as much as I could, ready for review!

**Comment by frankrousseau** [comment]
Let's apply the principles of [Building Open Source Communities](https://www.youtube.com/watch?v=uzxcILudFWM). I merge your PR. If there is something wrong that annoys someone (like the typo in the README), I guess that a new patch will be submitted.

Whatever thank you again for your work.

**Pull request merged**
