### PR TITLE
Fixing #221 : Fail with wrong identifier if the ss nb is longer than …

### PR DESCRIPTION
**Pull request by doubleface**
…13 digits + better description message

### CODE REVIEW

**Comment by doubleface** [comment]
You are right, here is the fixed version + the build. I cannot test it at the moment because my cozy is still under node 0.10 and does not work with the last version.

**Comment by frankrousseau** [comment]
@ZeHiro is it ok for merging?

**Comment by ZeHiro** [comment]
I couldn't test yet. Maybe tonight

**Comment by ZeHiro** [comment]
@frankrousseau 
Good to me,

**Comment by frankrousseau** [comment]
@ZeHiro You did the review, I let you merge it!

**Comment by frankrousseau** [comment]
Thx to both of you!

**Pull request merged**
