### PR TITLE
Correct UTC format issue

### PR DESCRIPTION
**Pull request by Peltoche**
That could lead to not find the factures to the bank operations

### CODE REVIEW

**Comment by Peltoche** [comment]
Hey @ZeHiro !

This PR mean to resolve this issue.
Before the use of moment().toISOString() lead to move the local time (UTC+1) to ISO format (UTC+0) and the issue you have explained. Now we don't use this function but parse the date manually to ISO and force it set the date to (YYYY-MM-DD)T00:00:00.000Z so they can match with the Kresus transaction.

Thanks for the two links, I wondered were else this error should be inserted. Now all should be good.

**Comment by Peltoche** [comment]
The test are ok locally, I don't know what can fail in the konnector system.... @frankrousseau an y idea?

**Comment by ZeHiro** [comment]
@Peltoche , good news :)

**Comment by frankrousseau** [comment]
Don't worry about tests, I will check what's wrong later. Thx to both of you!

**Pull request merged**
