### PR TITLE
Sfrbox et sfr mobile

### PR DESCRIPTION
**Pull request by doubleface**
This works also for red clients and has been tested by some users : https://forum.cozy.io/t/konnectors-nouveau-connecteur-pour-sfr/2348

### CODE REVIEW

**Comment by frankrousseau** [comment]
Hi @doubleface,

  Thank you for that set of new connectors. SFR customers will like it. About the code I have two remarks:

* Can you use the `Bill` model instead of `InternetBill` and set type field with *Internet* as value (on each bill)?
* Can you use make sure that there is no linting errors (`npm run lint`)?

**Comment by doubleface** [comment]
OK, I will take à look at it

**Comment by doubleface** [comment]
Bon, cette fois les tests n'échouent que à cause du module sncf. Donc à priori c'est bon.

**Comment by doubleface** [comment]
Ooups, this time, the unit tests only fail because of the sncf module. This one is the good one, I suppose.

**Comment by SomeAverageDev** [comment]
You will just need to add the locales for SFR MOBILE and you should be done for good !

**Comment by frankrousseau** [comment]
Thank you for the modification. I have two other changes to ask you before merging:

* Can you use `base_konnector` to make the description of your konnector lighter?
* Can you require directly the model `..//models/bill` instead of redescribing it and defining its queries?

**Comment by doubleface** [comment]
And it is done

**Comment by frankrousseau** [comment]
Thank you a lot. It's now included in the last release of konnectors!

**Pull request merged**
