### PR TITLE
Add SNCF konnector

### PR DESCRIPTION
**Pull request by Chocobozzz**
Add events and bills (without pdf) in Cozy. So we can see travels details in the calendar app :)

I'm sorry in advance, the code is ugly because the generated HTML by SNCF is a little bit difficult to parse (#frenchtech). Open to remarks.

Closes https://github.com/cozy-labs/konnectors/issues/205

### CODE REVIEW

**Comment by frankrousseau** [comment]
Thank you for that new konnector. I will be super glad to use it. It doesn't fetch the history. Is it something you could add?

**Comment by Chocobozzz** [comment]
Yep, but it would be just for the bills. I keep you in touch :)

**Comment by frankrousseau** [comment]
Another thing. Because we don't have the PDF file. Can you add a content field to the bill model and save details into it?

**Comment by Chocobozzz** [comment]
I pushed the modifications. Waiting for https://github.com/cozy-labs/konnectors/pull/223 before reformating.

**Comment by Chocobozzz** [comment]
Done.

**Comment by frankrousseau** [comment]
Thank you @Chocobozzz!

**Pull request merged**
