### PR TITLE
Numericable

### LINKED ISSUE #56: Numericable bills
Another Konnector idea.

### PR DESCRIPTION
**Pull request by nicofrand**
That should fix #56.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Thank you for this new konnector! Before merging it, it would be better if the code follows the Cozy guidelines: 
https://github.com/cozy/cozy-guidelines/#cozy-code-guidelines

What is missing: 

* replace `!` by `not` keyword.
* Lines should be < 80 chars. 

Can you handle it?

**Comment by nicofrand** [comment]
Yes I will.
Since you read it, could you tell me what was wrong with the following code please ?

```
Bill = cozydb.getModel 'Bill',
    vendor: {type: String, default: 'Internet'}
    type:
        type: String
        default: 'Internet'
    vendor:
        type: String
        default: 'Numéricable'
     date: Date
     amount: Number
```

I had to replace it with:
```
Bill = require '../models/bill'
```

I followed https://github.com/cozy-labs/konnectors/wiki#data-description-models

**Comment by frankrousseau** [comment]
I don't know what's wrong except the fact you declared the vendor field twice. Indentation doesn't look proper too.
But the real reason is probably that the Bill model is already declared in the model folder.

**Comment by nicofrand** [comment]
The indentation is only wrong because I copy/pasted this block wrong.
I am pretty sure I tried the vendor things twice too and just forgot to remove one of them once commented.

Why does the wiki says to use getModel if the model already declares it  then ?
(And by the way, why is there "vendor: type: String, default: 'Digital Ocean'" ? Digital Ocean should not be the default vendor)

**Comment by frankrousseau** [comment]
Great! Thank you @nicofrand for this konnector.
Setting vendor must be done for each bill. But the save_data_and_file layer do it for you.

About the Digital Ocean as a vendor it's a mistake that will be fixed soon.

Thank you again for the bug reports.

**Comment by nicofrand** [comment]
Where do you see that save_data_and_file already sets the vendor automatically ?

When it does, does it use the third parameter:
`.use(saveDataAndFile(log, Bill, 'numericable', ['bill']))`

I suggest to complete the wiki with those information.

**Comment by ZeHiro** [comment]
@nicofrand , the third parameter will set the vendor automatically, if it is not already set in the bill object you created when you parsed them form the website.

**Comment by nicofrand** [comment]
Thanks @ZeHiro , I updated the wiki so that is it clear now.

**Pull request merged**
