### PR TITLE
Fix test broken on travis

### PR DESCRIPTION
**Pull request by misstick**
It's difficult to maintain konnector environment because of tests that are broken; here is the list of broken test to fix:
 - [x] fix bad tabs,
 - [x] add slug for issue on `captain_train_konnector`,
 - [x] add missing translations,
 - [x] fix typo into tests.

### CODE REVIEW

**Comment by nicofrand** [comment]
Hi,

sorry but I don't get it… Why do you disable most of the tests ?

**Comment by misstick** [comment]
Hi @nicofrand; don't worry and take a look at the name of this PR :)
I should add a sentence to explain the checklist into description.

**Comment by nicofrand** [comment]
I did. But I don't understand why you would disable the tests instead of fixing the issues (hence "Don't kill the messenger") ?

**Comment by ZeHiro** [comment]
For konnector migration : https://github.com/cozy-labs/konnectors/blob/master/server/init/konnectors.coffee#L13

**Comment by misstick** [comment]
@ZeHiro : I prefer add a slug property to connector because "guessing" slug by its name is not really serious to my opinion. Anyway, I still use the way to ensure migration and keep consistency.

**Comment by ZeHiro** [comment]
@misstick I think the slug could even be set by konnctors directly from the filename (if possible). As a 2 files with the same filename are not possible in the same directory, I think it will ease the setup.

**Pull request merged**
