### PR TITLE
adding APRR invoices fetch

### PR DESCRIPTION
**Pull request by SomeAverageDev**
i included all required modifications and made a lint test

### CODE REVIEW

**Comment by SomeAverageDev** [comment]
there is a conflict with the facebook event in the local files...

**Comment by ZeHiro** [comment]
@SomeAverageDev github tells me it can be merged.

**Comment by SomeAverageDev** [comment]
I modified my files and added facebook translations

**Comment by SomeAverageDev** [comment]
hi @ZeHiro, 

the linter throws an error on lines

`    obj['ctl00$PlaceHolderMain$TextBoxLogin'] = requiredFields.login;
    obj['ctl00$PlaceHolderMain$TextBoxPass'] = requiredFields.password;
    obj['ctl00$PlaceHolderMain$ImageButtonConnection.x'] = Math.floor((Math.random() * 10) + 1);
    obj['ctl00$PlaceHolderMain$ImageButtonConnection.y'] = Math.floor((Math.random() * 10) + 1);
`
`
   82:9  error    ["ctl00$PlaceHolderMain$TextBoxLogin"] is better written in dot notation  dot-notation
   83:9  error    ["ctl00$PlaceHolderMain$TextBoxPass"] is better written in dot notation   dot-notation
`

but I don't see how i can change that, as the obj object is used to store all the input fields and pass them to the POST call.

**Comment by ZeHiro** [comment]
I merge it like this and I fix the lint error

**Pull request merged**
