### PR TITLE
Save file name and file mime for clean link to bankoperation

### PR DESCRIPTION
**Pull request by ZeHiro**
Fixes https://github.com/cozy-labs/konnectors/issues/52

This PR allows also to update already linked operations.

One question remains (just editorial) : 
do I rather use another name for fileName and fileMime ? (using only lower case field names)

### CODE REVIEW

**Comment by frankrousseau** [comment]
Thank you for working on this. But the binary object is an agnostic object. I think it's better if you save this at the bill level only. 
Another problem will be if the user changes the file name. It may happen rarely, I'm not sure we should handle it.

**Comment by ZeHiro** [comment]
OK. I'll rty to propose something else. A simple question, after a fast review of all the "bill import" konnectors, it appears PhoneBill and InternetBill have the same structure (codeBill has one more field), is there a goal for that? Couldn't there only be a "bill" structure? My point is that I plan to create a connector to import bills from Capitaine Train, so train bills. But I don't see the interest of creating a new specific structure (e.g. TrainBill) just for that. I would create a more generic structure.

**Comment by frankrousseau** [comment]
Sorry I just realised I never answered to your question. I totally agree that a Bill object with a type field would be better.

**Comment by ZeHiro** [comment]
OK. I'll see wht I can do for that. But a transition has to be done.

**Comment by frankrousseau** [comment]
Let's merge it and not worry about file name changing. Whatever the orginal name is better than no name.

**Comment by frankrousseau** [comment]
Thank you @ZeHiro

**Pull request merged**
