### PR TITLE
Add Ical feed connector

### PR DESCRIPTION
**Pull request by frankrousseau**
Add a connector to fetch data from an Ical feed on a regular basis.

It comes with a base object for connectors to make the development of connectors easier.

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Awesome :+1: 

The base konnector will simplify a lot some konnectors.

Just have a question: why do you use `var` instead of `let`?

**Comment by frankrousseau** [comment]
No reason :). What `let` does better than `var`?

**Comment by Chocobozzz** [comment]
I'm not an ES6 expert but I read some posts saying that we should use `let` instead of `var` with ES6.

This answer on stackexchange provides a good argumentation in my opinion: http://programmers.stackexchange.com/a/274352

**Comment by frankrousseau** [comment]
Ok, thanks for the tip!

**Pull request merged**
