### PR TITLE
Added Free Mobile Konnector

### PR DESCRIPTION
**Pull request by ZeHiro**
As mentionned in https://github.com/cozy-labs/konnectors/issues/62, here is the connector for Free Mobile bills

### CODE REVIEW

**Comment by ZeHiro** [comment]
Close, conflicts to resolve first

**Comment by frankrousseau** [comment]
What was wrong in your commit is that you pushed package.json deletion, and new link_bank_operation file and new BankOperation model. These file already exists and the package.json shouldn't be deleted.

What is expected in your commit:

* The konnector file
* The change in the locale file
* The change in the README

**Comment by ZeHiro** [comment]
Yes, the link_bank_operation file and BankOperation model file disapeared (problem in rebase) on my local machine and I pushed it inside my github repo.
package.json will also be updated (new dependancy, and update of the description).

**Comment by frankrousseau** [comment]
Ok, sounds good.

**Pull request closed without merging**
